name: eccomerce_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  remixicon: ^1.2.0
  iconsax: ^0.0.8
  flutter_otp_text_field: ^1.2.0
  expandable_page_view: ^1.0.17
  image_picker: ^1.1.2
  mobile_scanner: ^5.2.3
  palette_generator: ^0.3.3+4
  flutter_rating_bar: ^4.0.1
  buttons_tabbar: ^1.3.13
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  loader_overlay: ^5.0.0
  shimmer: ^3.0.0
  fluttertoast: ^9.0.0
  slider_button: ^2.1.0
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^31.2.10
  syncfusion_flutter_datepicker: ^31.2.10
  file_picker: ^10.3.6
  flutter_screenutil: ^5.9.3
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^9.0.0
  share_plus: ^12.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  http_parser: ^4.1.2
  device_info_plus: ^11.5.0
  font_awesome_flutter: ^10.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
